### ISSUE TITLE
Namespace all classes and rename some

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-oelib#398]
All classes should be properly PSR-4-namespaced, including the test cases and fixture classes, also also including the deprecated classes.

The namespacing schema should follow the already namespaced classes and the existing tests. If the test case names and the tested class names differ, the new names should follow the names of the test cases.

We need proper migrations and a class alias map (with the old classes being marked as deprecated and to be removed in oelib 4.0.0).

We should have one PR per renamed/moved class or namespace (if the classes are really small).

**Comment by oliverklee** [comment]
Concerning the naming: The Mappers need to change their name to have a `Mapper` suffix, e.g. `Mapper/Country` -> `Mapper/CountryMapper`.

**Comment by oliverklee** [comment]
And the `DataMapper` should change to `AbstractDataMapper`.

**Comment by Konafets** [comment]
`Tx_Oelib_List` must be renamed to something else because `List` is a reserved keyword in PHP (https://www.php.net/manual/en/reserved.keywords.php)

**Comment by oliverklee** [comment]
Then let's rename `List` to `Collection`.

**Comment by oliverklee** [comment]
And the view helpers all need to be renamed to `*ViewHelper`, and all move to the `ViewHelpers` namespace.

**Comment by oliverklee** [comment]
As the final step (after ever class has been namespaced), we should remove the corresponding exceptions from `phpcs.xml.dist`.

**Comment by oliverklee** [comment]
`Tx_Oelib_Mail` should change to `Email`.

**Comment by oliverklee** [comment]
And `Time` should become an interface as it's only there for the public constants.

**Comment by oliverklee** [comment]
`ConfigGheck` needs to become `ConfigurationCheck`, and `AbstractHeaderProxy` should become an interface `HeaderProxy`.

**Comment by Konafets** [comment]
I consider this as resolved and opt for closing.

**Comment by oliverklee** [comment]
No, there's still work to be done: https://github.com/oliverklee/ext-oelib/issues/398#issuecomment-734223860
