### ISSUE TITLE
Check/update/fix the language handling

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-oelib#410]
Check the `SalutationSwitcher` class, whether detection of the current FE and BE language is still correct in TYPO3 8/9/10, check whether the language labels are still read correctly, and fix any issues and add tests as needed.

Blocked by #467 and #498.

**Comment by Konafets** [comment]
Still seems to work with v9.

**Comment by oliverklee** [comment]
Thanks, closing then.
